"""
Constants shared between GUIs (Tkinter/Streamlit).
"""

# --- Calculation Types ---
CALC_TYPE_INCREMENTALE = "Incrementale"
CALC_TYPE_MEDIA = "Media"

# --- Repartition Logic ---
REPARTITION_LOGIC_ANNO = "Anno"
REPARTITION_LOGIC_MESE = "Mese"
REPARTITION_LOGIC_TRIMESTRE = "Trimestre"
REPARTITION_LOGIC_SETTIMANA = "Settimana"

# --- Distribution Profiles ---
PROFILE_EVEN = "even_distribution"
PROFILE_ANNUAL_PROGRESSIVE = "annual_progressive"
PROFILE_ANNUAL_PROGRESSIVE_WEEKDAY_BIAS = "annual_progressive_weekday_bias"
PROFILE_TRUE_ANNUAL_SINUSOIDAL = "true_annual_sinusoidal"
PROFILE_MONTHLY_SINUSOIDAL = "monthly_sinusoidal"
PROFILE_LEGACY_INTRA_PERIOD_PROGRESSIVE = "legacy_intra_period_progressive"
PROFILE_QUARTERLY_PROGRESSIVE = "quarterly_progressive"
PROFILE_QUARTERLY_SINUSOIDAL = "quarterly_sinusoidal"

# --- Repartition Parameters ---
WEIGHT_INITIAL_FACTOR_INC = 0.5
WEIGHT_FINAL_FACTOR_INC = 1.5
WEIGHT_INITIAL_FACTOR_AVG = 1.6
WEIGHT_FINAL_FACTOR_AVG = 0.4
SINE_AMPLITUDE_INCREMENTAL = 0.3
SINE_AMPLITUDE_MEDIA = 0.2
SINE_PHASE_OFFSET = 0
WEEKDAY_BIAS_FACTOR_INCREMENTAL = 0.8
WEEKDAY_BIAS_FACTOR_MEDIA = 1.1
DEVIATION_SCALE_FACTOR_AVG = 0.2

# --- Period Types ---
PERIOD_TYPES_RESULTS = ["Giorno", "Settimana", "Mese", "Trimestre"]


DISTRIBUTION_PROFILE_OPTIONS = [
    PROFILE_EVEN,
    PROFILE_ANNUAL_PROGRESSIVE,
    PROFILE_ANNUAL_PROGRESSIVE_WEEKDAY_BIAS,
    PROFILE_TRUE_ANNUAL_SINUSOIDAL,
    PROFILE_MONTHLY_SINUSOIDAL,
    PROFILE_LEGACY_INTRA_PERIOD_PROGRESSIVE,
    PROFILE_QUARTERLY_PROGRESSIVE,
    PROFILE_QUARTERLY_SINUSOIDAL,
    "event_based_spikes_or_dips",
]
REPARTITION_LOGIC_OPTIONS = [
    REPARTITION_LOGIC_ANNO,
    REPARTITION_LOGIC_MESE,
    REPARTITION_LOGIC_TRIMESTRE,
    REPARTITION_LOGIC_SETTIMANA,
]
KPI_CALC_TYPE_OPTIONS = [CALC_TYPE_INCREMENTALE, CALC_TYPE_MEDIA]
